### ISSUE TITLE
Infografia_Conceptos y fases de gestión de proyectos de software

### ISSUE THREAD

**Issue by Elisahadad** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Elisahadad#1]
[Infografia_Conceptos y fases de gestión de proyectos de software (2).pdf](https://github.com/user-attachments/files/16805150/Infografia_Conceptos.y.fases.de.gestion.de.proyectos.de.software.2.pdf)

**Comment by ka194** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
